version: "1.0"

services:
  # proxy:
  #   container_name: proxy
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: "unless-stopped"
  #   networks:
  #     - backend

  # server:
  #   container_name: server
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: mysql://root:password@localhost:3306/dev
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   restart: "unless-stopped"
  #   networks:
  #     - backend
  #   links:
  #     - mysql
  #   depends_on:
  #     - mysql
  #     - kafka
  redis:
    container_name: redis
    image: "redis:7-alpine"
    ports:
      - 6379:6379
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  kafka_data:
    driver: local
